src/Entity/Bestelling.php
<?php

namespace App\Entity;

use App\Repository\BestellingRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BestellingRepository::class)
 */
class Bestelling
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Menuitem::class, inversedBy="bestellings")
     */
    private $menuitem_id;

    /**
     * @ORM\ManyToOne(targetEntity=Reservering::class, inversedBy="bestellings")
     */
    private $reservering_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $aantal;

    /**
     * @ORM\Column(type="boolean")
     */
    private $staat_klaar;

    /**
     * @ORM\ManyToOne(targetEntity=Bon::class, inversedBy="bestellings")
     */
    private $bon_id;

    /**
     * @ORM\ManyToOne(targetEntity=Gerecht::class, inversedBy="bestellings")
     */
    private $gerecht_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMenuitemId(): ?Menuitem
    {
        return $this->menuitem_id;
    }

    public function setMenuitemId(?Menuitem $menuitem_id): self
    {
        $this->menuitem_id = $menuitem_id;

        return $this;
    }

    public function getReserveringId(): ?Reservering
    {
        return $this->reservering_id;
    }

    public function setReserveringId(?Reservering $reservering_id): self
    {
        $this->reservering_id = $reservering_id;

        return $this;
    }

    public function getAantal(): ?int
    {
        return $this->aantal;
    }

    public function setAantal(int $aantal): self
    {
        $this->aantal = $aantal;

        return $this;
    }

    public function getStaatKlaar(): ?bool
    {
        return $this->staat_klaar;
    }

    public function setStaatKlaar(bool $staat_klaar): self
    {
        $this->staat_klaar = $staat_klaar;

        return $this;
    }

    public function getBonId(): ?Bon
    {
        return $this->bon_id;
    }

    public function setBonId(?Bon $bon_id): self
    {
        $this->bon_id = $bon_id;

        return $this;
    }

    public function getGerechtId(): ?Gerecht
    {
        return $this->gerecht_id;
    }

    public function setGerechtId(?Gerecht $gerecht_id): self
    {
        $this->gerecht_id = $gerecht_id;

        return $this;
    }
}

src/Entity/Menuitem.php
<?php

namespace App\Entity;

use App\Repository\MenuitemRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MenuitemRepository::class)
 */
class Menuitem
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Subgerecht::class, inversedBy="menuitems")
     */
    private $subgerecht_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $naam;

    /**
     * @ORM\Column(type="float")
     */
    private $prijs;

    /**
     * @ORM\OneToMany(targetEntity=Bestelling::class, mappedBy="menuitem_id")
     */
    private $bestellings;

    public function __construct()
    {
        $this->bestellings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSubgerechtId(): ?Subgerecht
    {
        return $this->subgerecht_id;
    }

    public function setSubgerechtId(?Subgerecht $subgerecht_id): self
    {
        $this->subgerecht_id = $subgerecht_id;

        return $this;
    }

    public function getNaam(): ?string
    {
        return $this->naam;
    }

    public function setNaam(string $naam): self
    {
        $this->naam = $naam;

        return $this;
    }

    public function getPrijs(): ?float
    {
        return $this->prijs;
    }

    public function setPrijs(float $prijs): self
    {
        $this->prijs = $prijs;

        return $this;
    }

    /**
     * @return Collection|Bestelling[]
     */
    public function getBestellings(): Collection
    {
        return $this->bestellings;
    }

    public function addBestelling(Bestelling $bestelling): self
    {
        if (!$this->bestellings->contains($bestelling)) {
            $this->bestellings[] = $bestelling;
            $bestelling->setMenuitemId($this);
        }

        return $this;
    }

    public function removeBestelling(Bestelling $bestelling): self
    {
        if ($this->bestellings->removeElement($bestelling)) {
            // set the owning side to null (unless already changed)
            if ($bestelling->getMenuitemId() === $this) {
                $bestelling->setMenuitemId(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getNaam();
    }
}

src/Entity/Reservering.php
<?php

namespace App\Entity;

use App\Repository\ReserveringRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReserveringRepository::class)
 */
class Reservering
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Klant::class, inversedBy="reserverings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $klant_id;

    /**
     * @ORM\ManyToOne(targetEntity=Tafel::class, inversedBy="reserverings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $tafel_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $aantal_personen;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datum;

    /**
     * @ORM\OneToOne(targetEntity=Bon::class, mappedBy="reservering_id", cascade={"persist", "remove"})
     */
    private $bon;

    /**
     * @ORM\OneToMany(targetEntity=Bestelling::class, mappedBy="reservering_id")
     */
    private $bestellings;

    public function __construct()
    {
        $this->bestellings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getKlantId(): ?Klant
    {
        return $this->klant_id;
    }

    public function setKlantId(?Klant $klant_id): self
    {
        $this->klant_id = $klant_id;

        return $this;
    }

    public function getTafelId(): ?Tafel
    {
        return $this->tafel_id;
    }

    public function setTafelId(?Tafel $tafel_id): self
    {
        $this->tafel_id = $tafel_id;

        return $this;
    }

    public function getAantalPersonen(): ?int
    {
        return $this->aantal_personen;
    }

    public function setAantalPersonen(int $aantal_personen): self
    {
        $this->aantal_personen = $aantal_personen;

        return $this;
    }

    public function getDatum(): ?\DateTimeInterface
    {
        return $this->datum;
    }

    public function setDatum(\DateTimeInterface $datum): self
    {
        $this->datum = $datum;

        return $this;
    }

    public function getBon(): ?Bon
    {
        return $this->bon;
    }

    public function setBon(?Bon $bon): self
    {
        // unset the owning side of the relation if necessary
        if ($bon === null && $this->bon !== null) {
            $this->bon->setReserveringId(null);
        }

        // set the owning side of the relation if necessary
        if ($bon !== null && $bon->getReserveringId() !== $this) {
            $bon->setReserveringId($this);
        }

        $this->bon = $bon;

        return $this;
    }

    /**
     * @return Collection|Bestelling[]
     */
    public function getBestellings(): Collection
    {
        return $this->bestellings;
    }

    public function addBestelling(Bestelling $bestelling): self
    {
        if (!$this->bestellings->contains($bestelling)) {
            $this->bestellings[] = $bestelling;
            $bestelling->setReserveringId($this);
        }

        return $this;
    }

    public function removeBestelling(Bestelling $bestelling): self
    {
        if ($this->bestellings->removeElement($bestelling)) {
            // set the owning side to null (unless already changed)
            if ($bestelling->getReserveringId() === $this) {
                $bestelling->setReserveringId(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getKlantId();
    }
}

src/Form/BestellingType.php
<?php

namespace App\Form;

use App\Entity\Bestelling;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BestellingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('aantal')
            ->add('staat_klaar')
            ->add('menuitem_id')
            ->add('reservering_id')
//            ->add('bon_id')
            ->add('gerecht_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Bestelling::class,
        ]);
    }
}

src/Controller/BestellingController.php
<?php

namespace App\Controller;

use App\Entity\Bestelling;
use App\Form\BestellingType;
use App\Repository\BestellingRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/bestelling")
 */
class BestellingController extends AbstractController
{
    /**
     * @Route("/", name="bestelling_index", methods={"GET"})
     */
    public function index(BestellingRepository $bestellingRepository): Response
    {
        return $this->render('bestelling/index.html.twig', [
            'bestellings' => $bestellingRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="bestelling_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $bestelling = new Bestelling();
        $form = $this->createForm(BestellingType::class, $bestelling);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($bestelling);
            $entityManager->flush();

            return $this->redirectToRoute('bestelling_index');
        }

        return $this->render('bestelling/new.html.twig', [
            'bestelling' => $bestelling,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="bestelling_show", methods={"GET"})
     */
    public function show(Bestelling $bestelling): Response
    {
        return $this->render('bestelling/show.html.twig', [
            'bestelling' => $bestelling,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="bestelling_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Bestelling $bestelling): Response
    {
        $form = $this->createForm(BestellingType::class, $bestelling);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('bestelling_index');
        }

        return $this->render('bestelling/edit.html.twig', [
            'bestelling' => $bestelling,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="bestelling_delete", methods={"POST"})
     */
    public function delete(Request $request, Bestelling $bestelling): Response
    {
        if ($this->isCsrfTokenValid('delete'.$bestelling->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($bestelling);
            $entityManager->flush();
        }

        return $this->redirectToRoute('bestelling_index');
    }
}

templates/bestelling/_delete_form.html.twig
<form method="post" action="{{ path('bestelling_delete', {'id': bestelling.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ bestelling.id) }}">
    <button class="btn"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
</form>

templates/bestelling/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/bestelling/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Bestelling{% endblock %}

{% block body %}
    <h1>Edit Bestelling</h1>

    {{ include('bestelling/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('bestelling_index') }}">back to list</a>

    {{ include('bestelling/_delete_form.html.twig') }}
{% endblock %}

templates/bestelling/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bestelling index{% endblock %}

{% block body %}
    <h1>Bestelling index</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Aantal</th>
            <th>Klant Naam</th>
            <th>Tafel</th>
            <th>Gerecht</th>
            <th>Staat klaar</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for bestelling in bestellings %}
            <tr>
                <td>{{ bestelling.id }}</td>
                <td>{{ bestelling.aantal }}</td>
                <td>{{ bestelling.reserveringId }}</td>
                <td>{{ bestelling.reserveringId.tafelId }}</td>
                <td>{{ bestelling.menuitemId.subgerechtId.gerechtId }}</td>
                <td>{{ bestelling.staatKlaar ? 'Ja' : 'Nee' }}</td>
                <td>
                    <a href="{{ path('bestelling_show', {'id': bestelling.id}) }}">show</a>
                    <a href="{{ path('bestelling_edit', {'id': bestelling.id}) }}"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('bestelling_new') }}">Create new</a>
{% endblock %}

templates/bestelling/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Bestelling{% endblock %}

{% block body %}
    <h1>Create new Bestelling</h1>

    {{ include('bestelling/_form.html.twig') }}

    <a href="{{ path('bestelling_index') }}">back to list</a>
{% endblock %}

templates/bestelling/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bestelling{% endblock %}

{% block body %}
    <h1>Bestelling</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ bestelling.id }}</td>
        </tr>
        <tr>
            <th>Aantal</th>
            <td>{{ bestelling.aantal }}</td>
        </tr>
        <tr>
            <th>Staat_klaar</th>
            <td>{{ bestelling.staatKlaar ? 'Yes' : 'No' }}</td>
        </tr>
        </tbody>
    </table>

    <a href="{{ path('bestelling_index') }}">back to list</a>

    <a href="{{ path('bestelling_edit', {'id': bestelling.id}) }}">edit</a>

    {{ include('bestelling/_delete_form.html.twig') }}
{% endblock %}